# frozen_string_literal: true
# test/aia/rule_router_test.rb

require_relative '../test_helper'
require_relative '../../lib/aia'
require 'tmpdir'

class RuleRouterTest < Minitest::Test
  def setup
    @config = create_test_config
    AIA.stubs(:config).returns(@config)
  end

  def teardown
    super
  end

  def test_initialization
    router = AIA::RuleRouter.new
    refute_nil router
  end

  def test_evaluate_does_nothing_when_rules_disabled
    @config.rules.enabled = false
    router = AIA::RuleRouter.new

    # Should not raise
    router.evaluate(@config)
  end

  def test_evaluate_runs_with_empty_context
    @config.rules.enabled = true
    @config.context_files = []
    router = AIA::RuleRouter.new

    # Should not raise
    router.evaluate(@config)
  end

  def test_evaluate_turn_does_nothing_when_rules_disabled
    @config.rules.enabled = false
    router = AIA::RuleRouter.new

    # Should not raise
    router.evaluate_turn(@config, "Hello")
  end

  def test_evaluate_turn_runs_with_input
    @config.rules.enabled = true
    @config.context_files = []
    router = AIA::RuleRouter.new

    # Should not raise
    router.evaluate_turn(@config, "Tell me about Ruby")
  end

  def test_evaluate_with_image_context_file
    @config.rules.enabled = true
    @config.flags.verbose = false

    temp_file = File.join(Dir.tmpdir, 'test_image.png')
    File.write(temp_file, 'fake png data')
    @config.context_files = [temp_file]

    router = AIA::RuleRouter.new
    # Should not raise — rule fires but only logs at verbose
    router.evaluate(@config)

    File.delete(temp_file) if File.exist?(temp_file)
  end

  def test_evaluate_with_image_populates_suggestions
    @config.rules.enabled = true
    @config.flags.verbose = true

    temp_file = File.join(Dir.tmpdir, 'test_image_verbose.png')
    File.write(temp_file, 'fake png data')
    @config.context_files = [temp_file]

    router = AIA::RuleRouter.new
    router.evaluate(@config)

    # Verify suggestions were generated by the rule engine
    suggestions = router.instance_variable_get(:@suggestions)
    assert suggestions.any? { |s| s[:value].include?("vision-capable model recommended") }

    File.delete(temp_file) if File.exist?(temp_file)
  end

  private

  def create_test_config
    OpenStruct.new(
      models: [OpenStruct.new(name: 'gpt-4o-mini', role: nil)],
      pipeline: [],
      context_files: [],
      mcp_servers: [],
      flags: OpenStruct.new(
        chat: false,
        debug: false,
        verbose: false,
        consensus: false
      ),
      rules: OpenStruct.new(
        dir: nil,
        enabled: false
      )
    )
  end
end
